title: FSociety.pt
description: Infraestrutura Empresarial Segura | Four-Legged Firewall
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

# Metadados
author: Ryan Barbosa, Hugo Correia, Igor Ara√∫jo
logo: /assets/images/fsociety-logo. png

# Mostrar link para repo
show_downloads: false

# Force rebuild
version: 2
